Refactor/kick pid library
bit-bots/bitbots_motion pull request #124
Opened 2020-01-20 13:45 UTC by timonegk

## Proposed changes

## Related issues

## Necessary checks
- [x] Update package version
- [x] Run linters
- [x] Run `catkin build`
- [ ] Write documentation
- [x] Test on your machine
- [ ] Test on the robot

2020-11-23 11:49 UTC, SammyRamone commented
this is currently only a draft. is it finished and should be tested ?

2021-01-19 15:35 UTC, timonegk commented
I rebased this to the current master, please review and test.

2021-01-19 15:38 UTC, SammyRamone requested changes

2021-01-19 15:38 UTC, SammyRamone commented on bitbots_dynamic_kick/cfg/bitbots_dynamic_kick_params.cfg
> +                 0, min=1, max=500)
there should be no default values in the .cfg but only in the config files. This can lead to issues. just specify the min and max value here

2021-01-19 15:46 UTC, SammyRamone approved these changes

2021-01-19 16:16 UTC, merged