hcm: fix smoothing in fall checker
bit-bots/bitbots_motion pull request #197
Opened 2021-01-21 10:01 UTC by SammyRamone

## Proposed changes
Fixes the missing smoothing threshold in the FallChecker. It was previously only used when the FallChecker was used through the classifier class.
The threshold prevents invoking fall measurements after a false positive due to message outliers.

## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Put the PR on our Project board

2021-01-21 10:02 UTC, SammyRamone commented
still needs some testing before merging to master

2021-01-21 15:15 UTC, Flova requested changes

2021-01-21 15:15 UTC, Flova commented on bitbots_hcm/src/bitbots_hcm/fall_checker.py
> +                    result = 0
To clarify the return value we could use `self.STABLE` instad of 0

2021-01-21 15:15 UTC, Flova commented on bitbots_hcm/src/bitbots_hcm/fall_checker.py
> +                result = 0
Same here

2021-01-21 18:18 UTC, Flova approved these changes

2021-01-22 08:49 UTC, SammyRamone commented
works like the previous code, there are other issues but I added them here https://github.com/bit-bots/bitbots_motion/issues/200

2021-01-22 08:49 UTC, merged