Rate.sleep issues in sim
bit-bots/bitbots_motion pull request #258
Opened 2021-05-31 16:16 UTC by SammyRamone

## Proposed changes
The rospy and roscpp implementation of rate.sleep() does not work correctly when the specified rate is higher than the simulation rate. We need to handle this explicitly.

## Necessary checks
- [ ] Update package version
- [ ] Run `catkin build`
- [ ] Write documentation
- [ ] Create issues for future work
- [ ] Test on your machine
- [ ] Test on the robot
- [ ] Put the PR on our Project board

2021-05-31 17:23 UTC, Flova commented on bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py
> +import bitbots_ros_patches
Is this second import nessesary?

2021-06-01 12:03 UTC, timonegk requested changes

2021-06-01 12:03 UTC, timonegk commented on bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py
> +# !/usr/bin/env python3
```suggestion
```

2021-06-01 12:03 UTC, timonegk commented on bitbots_hcm/src/bitbots_hcm/humanoid_control_module.py
> +import time
```suggestion
```

2021-06-02 12:09 UTC, timonegk approved these changes

2021-06-02 13:14 UTC, merged